import os
import shutil
import tarfile
import json
from datetime import datetime

def run_automated_backup():
    print("[*] Launching Automated Infrastructure Archival Engine...")
    print("=========================================================")
    
    # Define our source and target locations
    source_dir = "./"
    vault_dir = "./backup_vault"
    
    # Ensure the backup vault folder exists
    os.makedirs(vault_dir, exist_ok=True)
    
    # 1. Scan for backup artifacts generated by our rotation tools (.bak files)
    files_to_backup = [f for f in os.listdir(source_dir) if f.endswith('.bak')]
    
    if not files_to_backup:
        print("[ℹ️ INFO] No rotated log artifacts (.bak) found to archive. Workspace is clean.")
        return

    print(f"[+] Found {len(files_to_backup)} stale log files ready for secure containment.")
    
    # 2. Create a timestamped name for our archive bundle
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    archive_filename = f"log_archive_{timestamp}.tar.gz"
    archive_path = os.path.join(vault_dir, archive_filename)
    
    # 3. Compress the target files into a secure tarball
    print(f"[*] Packaging files into compressed vault bundle: {archive_filename}...")
    with tarfile.open(archive_path, "w:gz") as tar:
        for file in files_to_backup:
            tar.add(file)
            print(f"   -> Encapsulated: {file}")
            
    # 4. Safely purge the raw local copies now that they are secured in the tarball
    for file in files_to_backup:
        os.remove(file)
    print("[+] Raw log artifacts purged safely from active workspace.")

    # 5. Generate a telemetry audit report for security review
    report_data = {
        "backup_timestamp": datetime.now().isoformat(),
        "archive_package": archive_filename,
        "vault_destination": vault_dir,
        "files_secured_count": len(files_to_backup),
        "files_list": files_to_backup,
        "status": "SUCCESS"
    }
    
    report_path = os.path.join(vault_dir, f"backup_report_{timestamp}.json")
    with open(report_path, "w", encoding="utf-8") as report_file:
        json.dump(report_data, report_file, indent=4)
        
    print(f"[🎉 SUCCESS] Backup engine completed. Audit summary written to {os.path.basename(report_path)}")

if __name__ == "__main__":
    run_automated_backup()